### ISSUE TITLE
The keyboard lights for this applet have stopped working

### ISSUE THREAD

**Issue by yuguang** [daskeyboard/daskeyboard-applet--stock-quote-usa#4]
I suspect there is an error when fetching the ticker symbol data from IEX. When I go to add a new stock quote and click save, the save dialog does not complete and move on to the next screen.

**Comment by fabiendv** [comment]
This issue is related to https://github.com/daskeyboard/daskeyboard-applet--stock-quote-usa/issues/5

We are currently looking into another API.

Any help would be highly appreciate.
